import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen overflow-clip`}
      >
        {children}
        <div className="absolute bottom-0 w-full bg-black text-white text-center py-5" style={{ zIndex: 1000 }}>
          This site is currently being built and is not yet complete. Feel free to explore, but please note that some info may be missing or incomplete.
        </div>
      </body>
    </html>
  );
}
